# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15GvrnW7BkhDKBPMV2SMPSNY_SMFGkfIR
"""

from sklearn import metrics
from sklearn.svm import LinearSVC

# features 1: sim, 0:não
# pelo longo
# baixinho
# late

#features para o porco = 1
porco1 = [0,1,0]
porco2 = [0,1,1]
porco3 = [1,1,0]

#features para o cachorro = 0
cachorro1 = [0,1,1]
cachorro2 = [1,0,1]
cachorro3 = [1,1,1]

#agrupamento de dados
data = [porco1, porco2, porco3, cachorro1, cachorro2, cachorro3]
#classificacao dos dados
classificacao = [1, 1, 1, 0, 0, 0]

#instancia do LinearSVC
model = LinearSVC()
#treinamento 
model.fit(data, classificacao)

#animal de teste
test_animal = [1,0,1]
#teste para previsão
model.predict([test_animal])

#teste em massa de dados
test_animal1 = [0,0,0]
test_animal2 = [1,1,0]
test_animal3 = [0,0,1]
test_animal4 = [1,1,1]
test_all = [test_animal1,test_animal2,test_animal3,test_animal4]
#previsão de massa de dados
model.predict(test_all)